### ISSUE TITLE
"Nothing to import!"

### ISSUE THREAD

**Issue by csmit86** [ogxd/blender-importer-unity#1]
In Unity 2019.3.1 it says ""Nothing to import!" when importing it as a custom package.
To make it work I downloaded the zip and copied the files from the plugins folder.

Works great! Thanks :)

**Comment by ogxd** [comment]
Thanks for the feedback !
I tried on Unity 2019.3.2f1 & 2019.3.0f6 but I wasn't able to reproduce the issue. It might be related to the custom packer
