### ISSUE TITLE
Surprising Early Return

### ISSUE THREAD

**Issue by floere** [ogxd/blender-importer-unity#2]
Hi! Thanks for the plugin, first of all 😊
I'm wondering about the very early return here: https://github.com/ogxd/blender-importer-unity/blob/3ebb71b3f9d2b9cc7652946ba07c89ead9d67f21/Assets/Plugins/BlenderImporter/Editor/BlenderImporter.cs#L36
Is the intention to tell people not to use the plugin anymore?

**Comment by ogxd** [comment]
Hello @floere,
At first, the plugin was meant for Blender to Unity, but while coding the thing, I found out that it might be useful for any model, weither it comes from blender, maya, C4D, ... as long as the orientation doesn't match Unity's orientation.
I put this project on hold to think about how to generalize this plugin. The return is probably a mistake, it is likely that I was about to refactor. I'm removing this early return. As is, the plugin is useable, but users have to get into that switch if they want to customize orientation.

**Comment by floere** [comment]
@ogxd Thanks for the infos, Olivier! 😊
